name = "SpreadsheetFunctions"
uuid = "e73f9a84-cd51-4b71-8300-a5bd9a7ba7a5"
authors = ["Mary McGrath <m.c.mcgrath13@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
DataFrames = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
